### ISSUE TITLE
Exception when any data is sent after connecting to the library

### ISSUE THREAD

**Issue by czardoz** [czardoz/libtelnetsrv#2]
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czardoz/git/libtelnetsrv/libtelnetsrv/paramiko_ssh.py", line 240, in start_pty_request
    self.pty_handler(request, self.client_address, self.tcp_server)
  File "/home/czardoz/git/libtelnetsrv/libtelnetsrv/paramiko_ssh.py", line 75, in __init__
    super(MixedPtyHandler, self).__init__(*args)
  File "/home/czardoz/git/libtelnetsrv/libtelnetsrv/paramiko_ssh.py", line 33, in __init__
    super(TelnetToPtyHandler, self).__init__(*args)
  File "/home/czardoz/git/libtelnetsrv/libtelnetsrv/threaded.py", line 21, in __init__
    TelnetHandlerBase.__init__(self, request, client_address, server)
  File "/home/czardoz/git/libtelnetsrv/libtelnetsrv/main.py", line 484, in __init__
    socketserver.BaseRequestHandler.__init__(self, request, client_address, server)
  File "/usr/lib/python3.4/socketserver.py", line 673, in __init__
    self.handle()
  File "/home/czardoz/git/libtelnetsrv/libtelnetsrv/main.py", line 1034, in handle
    raw_input = self.readline(prompt=self.PROMPT).strip()
  File "/home/czardoz/git/libtelnetsrv/libtelnetsrv/main.py", line 758, in readline
    if ord(c) < 32:
TypeError: ord() expected string of length 1, but int found
```

This is because of incompatibilities in Python 2 and 3. In case of Python3, the variable is already an `int` because the container is a `bytes` object.

**Comment by czardoz** [comment]
In Python3, `socket.recv` returns a `bytes()` object, which is basically a collection of `int`s. 

The problem lies in `_inputcooker_getc()` method: 

```
    def _inputcooker_getc(self, block=True):
        """Get one character from the raw queue. Optionally blocking.
        Raise EOFError on end of stream. SHOULD ONLY BE CALLED FROM THE
        INPUT COOKER."""
        if self.rawq:
            ret = self.rawq[0]
            self.rawq = self.rawq[1:]
            return ret
        if not block:
            if not self.inputcooker_socket_ready():
                return b''
        ret = self.sock.recv(20)
        self.eof = not ret
        self.rawq = self.rawq + ret
        if self.eof:
            raise EOFError
        return self._inputcooker_getc(block)
```

Should probably convert the int to a `chr` before doing anything with it, but need to think further, because `self.rawq` is a `bytes` object.
